
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: postgres
  password: 12201995
  host: 172.18.0.2
  encoding: UTF8

development:
  <<: *default
  database: My_picture_development

  
test:
  <<: *default
  database: My_picture_test

production:
  <<: *default
  database: My_picture_production
  username: My_picture
  password: <%= ENV['MY_PICTURE_DATABASE_PASSWORD'] %>
