# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 900ff75d7916461984ef1c1e1b3f85b0f0a54b718fc85d031f6aa18d9e2a79c7c5fe47bdf2841ad537fcdbefa77ac2e5731facaa8475333cc0f6fbb4f440ea0a

test:
  secret_key_base: d93eda9e468ef622a87e5ab700c1ec1810ee1975fe8a0a8aacfb384bb191e806935a9e2f800d7b5419c982e7ad914820622eac3f8e39da7f9cf621f6941540ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
