version: '3'
services:
  db:
    image: postgres
    container_name: db
  web:
    build: .
    container_name: web
    command: rails s -b 0.0.0.0
    ports: 
     - "3000:3000"
    volumes:
      - .:/my_insta
    links:
      - db