# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ab57ce528a86da0ff34ffb6ac5875f7649cb56329050ed2d0a10699d021c188d7d4fcdc030fcf3572671b8b127f2a369c9bced3569fc25c3333c442a1889421

test:
  secret_key_base: 4e3f3714c08885d5ded238da8d5b5a9f5cbeb3728f833fb24840623a85ea0466bea02ef403c7d633cfd7c6abbf85c66c769570b5488d2262cb5d03620feb1da1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
